In [1]:
import numpy as np

In [2]:
# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

In [3]:
# Create random input and output data
x = np.random.randn(N, D_in)
y = np.random.randn(N, D_out)

In [12]:
x, x.shape, len(x[0]), len(x), x[0]

(array([[ 0.23173758,  0.07768082, -0.81151005, ...,  0.13366115,
          0.38262193, -0.17322908],
        [-1.01556562,  0.54989327,  0.35519727, ...,  1.49020514,
         -0.7894303 , -0.60477514],
        [ 0.95404179,  0.9292738 ,  0.48654393, ...,  0.24442791,
          0.53461204, -0.0067798 ],
        ...,
        [-0.27974454,  1.25207046,  0.90074141, ..., -0.87528384,
          0.53759343,  1.04825228],
        [-0.06099425, -0.02729887,  0.07422885, ..., -1.06667527,
          0.58600819,  0.48111297],
        [-0.7779682 ,  0.72767474,  1.01591952, ..., -2.01295008,
         -0.70630441,  0.77643524]]),
 (64, 1000),
 1000,
 64,
 array([ 2.31737582e-01,  7.76808198e-02, -8.11510054e-01,  3.87044912e-01,
        -7.86732541e-01,  2.04250066e-01, -5.37396959e-01,  5.36149099e-01,
        -1.33780416e+00, -8.56095998e-01, -1.01399826e+00, -3.87420677e-01,
         2.48424328e-01,  4.83728158e-01,  1.11791309e+00,  1.23004100e+00,
        -2.02012692e-01, -8.73838101e-01, -4

In [13]:
# Randomly initialize weights
w1 = np.random.randn(D_in, H)
w2 = np.random.randn(H, D_out)

In [15]:
learning_rate = 1e-6

# Forward pass: compute predicted y
h = x.dot(w1)
h_relu = np.maximum(h, 0)
y_pred = h_relu.dot(w2)

# Compute and print loss
loss = np.square(y_pred - y).sum()
print(0, loss)

0 44577026.33715746


In [16]:
h, h_relu, y_pred

(array([[-22.66989421,   8.68820071,  -0.35697273, ..., -13.64257743,
          11.89260981,  32.19480814],
        [ -3.45892783,   0.2390356 ,  -7.68018299, ..., -17.99122697,
           7.18707391, -30.84233711],
        [-33.19602487, -40.85958104,   3.96449357, ...,  -7.83663151,
         -25.08303808,  -6.08492199],
        ...,
        [-20.01393155, -12.03332801, -13.17870164, ...,  -7.29961104,
           7.42154535, -11.55372208],
        [-80.24253539,  15.32701595,  -9.64131812, ..., -47.56463103,
          -8.21383274, -54.89069019],
        [-57.47744582, -19.97142508,  -4.0902493 , ...,  -6.44301066,
          33.70773558,  -3.36239723]]),
 array([[ 0.        ,  8.68820071,  0.        , ...,  0.        ,
         11.89260981, 32.19480814],
        [ 0.        ,  0.2390356 ,  0.        , ...,  0.        ,
          7.18707391,  0.        ],
        [ 0.        ,  0.        ,  3.96449357, ...,  0.        ,
          0.        ,  0.        ],
        ...,
        [ 0.      

In [ ]:

    # Backprop to compute gradients of w1 and w2 with respect to loss
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.T.dot(grad_y_pred)
    grad_h_relu = grad_y_pred.dot(w2.T)
    grad_h = grad_h_relu.copy()
    grad_h[h < 0] = 0
    grad_w1 = x.T.dot(grad_h)

    # Update weights
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2